### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by bianci5** [reverse-shell/routersploit#100]
Sorry it doesn't work again:
`davide@bianci5 ~/routersploit $ pip install -r requirements.txt 
Requirement already satisfied (use --upgrade to upgrade): gnureadline>=6.3.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): requests>=2.9.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Collecting paramiko>=1.16.0 (from -r requirements.txt (line 3))
  Using cached paramiko-2.0.0-py2.py3-none-any.whl
Collecting beautifulsoup4>=4.4.1 (from -r requirements.txt (line 4))
  Using cached beautifulsoup4-4.4.1-py2-none-any.whl
Collecting pysnmp>=4.3.2 (from -r requirements.txt (line 5))
  Using cached pysnmp-4.3.2-py2.py3-none-any.whl
Collecting cryptography>=1.1 (from paramiko>=1.16.0->-r requirements.txt (line 3))
  Using cached cryptography-1.4.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from paramiko>=1.16.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.4.1 in /usr/lib/python2.7/dist-packages (from pysnmp>=4.3.2->-r requirements.txt (line 5))
Collecting pysmi (from pysnmp>=4.3.2->-r requirements.txt (line 5))
  Using cached pysmi-0.0.7-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 3))
Collecting cffi>=1.4.1 (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 3))
  Using cached cffi-1.6.0.tar.gz
Collecting ply (from pysmi->pysnmp>=4.3.2->-r requirements.txt (line 5))
  Using cached ply-3.8.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 3))
Installing collected packages: cffi, cryptography, paramiko, beautifulsoup4, ply, pysmi, pysnmp
  Running setup.py install for cffi ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-FaqAeH/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TmQYY7-record/install-record.txt --single-version-externally-managed --compile:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/gc_weakref.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/verifier.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/lock.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/api.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/commontypes.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/__init__.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/recompiler.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/cparser.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/model.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/_embedding.h -> build/lib.linux-x86_64-2.7/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/c
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: File o directory non esistente
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-FaqAeH/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TmQYY7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-FaqAeH/cffi/
davide@bianci5 ~/routersploit $ 
`

**Comment by bianci5** [comment]
davide@bianci5 ~/routersploit $ ./rsf.py 
Traceback (most recent call last):
  File "./rsf.py", line 3, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/home/davide/routersploit/routersploit/__init__.py", line 1, in <module>
    from routersploit.utils import (
  File "/home/davide/routersploit/routersploit/utils.py", line 19, in <module>
    import requests
ImportError: No module named requests

**Comment by fwkz** [comment]
sudo pip install -r requirements.txt

**Comment by bianci5** [comment]
`davide@bianci5 ~/routersploit $ sudo pip install -r requirements.txt 
[sudo] password for davide: 
The directory '/home/davide/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/davide/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): gnureadline>=6.3.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): requests>=2.9.1 in /usr/local/lib/python2.7/dist-packages/requests-2.10.0-py2.7.egg (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): paramiko>=1.16.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4>=4.4.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): pysnmp>=4.3.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): cryptography>=1.1 in /usr/local/lib/python2.7/dist-packages (from paramiko>=1.16.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from paramiko>=1.16.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.4.1 in /usr/lib/python2.7/dist-packages (from pysnmp>=4.3.2->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): pysmi in /usr/local/lib/python2.7/dist-packages (from pysnmp>=4.3.2->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): ply in /usr/local/lib/python2.7/dist-packages (from pysmi->pysnmp>=4.3.2->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 3))
`

**Comment by fwkz** [comment]
https://github.com/reverse-shell/routersploit/issues/101#issuecomment-227090773

**Comment by bianci5** [comment]
you can close this issue
