### ISSUE TITLE
Is there a place to chat about routersploit?

### ISSUE THREAD

**Issue by wgwz** [reverse-shell/routersploit#105]
So I have had some basic questions about what routersploit does and how to use it. I think it would be great to have an IRC channel for it. Perhaps there is a place to chat about this already. Any thoughts/plans for a channel?

**Comment by BenjaminHCCarr** [comment]
While I am a longtime IRC user, I think https://gitter.im with their github integration makes the most sense, but @reverse-shell / one of the repo owners would need to launch it.

**Comment by lucyoa** [comment]
@wgwz  @BenjaminHCCarr Cool idea, I created chat: https://gitter.im/reverse-shell/routersploit
