### ISSUE TITLE
Fix colors on windows!

### ISSUE THREAD

**Issue by its0x08** [reverse-shell/routersploit#133]
colors on windows doesn't work!
please fix it

**Comment by lucyoa** [comment]
We do not support Windows - nevertheless I'm leaving issue open

**Comment by 0BuRner** [comment]
As it, some colors do work, some don't.
![image](https://cloud.githubusercontent.com/assets/1845905/21236810/c3f1ada4-c2fc-11e6-8040-a9a09ea15911.png)

**Comment by lucyoa** [comment]
We are adding this to backlog. We do not officially support windows environment.

**Comment by its0x08** [comment]
I dont support that system either i was just courious ... :P !
thanks for your time .
