### ISSUE TITLE
Vulnerability found in my router but....

### ISSUE THREAD

**Issue by Virgula0** [reverse-shell/routersploit#137]
I have found a vulnerability in my router (like image down), but I don't understand what can I do with this alphanumeric output....
![Router Git Hub](http://i68.tinypic.com/257m8uw.png)
Can someone help me?

Thanks!

**Comment by m0sia** [comment]
It is a hashed password.

Your password is "5up", default password for TP-Link.

**Comment by Virgula0** [comment]
There are too many encrypted password with username root, admin,bin,deamon,adm,lp,sync ecc.... how can I decrypt them?
But , above of all, are that the default password for the admin control panel in the address: 192.168.1.1??

**Comment by m0sia** [comment]
1. root/Admin password from /etc/shadow file is "5up"
2. You can use tools like "john the ripper"(aka john) or oclhashcat to recover hashed passwords using some kind of brute force. Supply those "alphanumeric output" to john and you will see that the password is "5up".
3. All the other accounts don't have a password and probably don't have valid shell in /etc/passwd

It will be a good idea to start with educating yourself about linux, linux user management and basic cryptography.

**Comment by Virgula0** [comment]
Ok i have understand except a thing.... The default password contained in the shadow file with username root and admin.... Are passwords for what?

**Comment by Themercee** [comment]
they are passwords use to login on the router. For exemple, if a SSH service is up on the router, for remote administration, you will supply the user and password to connect. If you don't know what SSH is, go read on it :)

**Comment by lucyoa** [comment]
Everything is clear now, closing

**Comment by dizcza** [comment]
Are there other ways to make use of Admin:5up or root:5up creds on TP-link routers expect for SSH login? What other ports can be opened in a router such that these creds work?

**Comment by 0BuRner** [comment]
@dizcza: use nmap to find the open ports on your router

**Comment by dizcza** [comment]
@0BuRner you obviously wouldn't try `up5` password for http router admin page authentification even though nmap scan shows that 80 and 443 router ports are opened in most cases.

I'm asking what kind of services a router theoretically can run such that someone is able to connect to via the creds above (possibly get internal access to unix system, shell). Except for ssh, of course. For example, database services like mysql have nothing to do with router unix creds.

**Comment by 0BuRner** [comment]
For example, depending on your ISP, your device may have a non-standard configuration, where SSH port is open or other services with same credentials as the root user.
I even found one day a router of different brand (so different configuration) but with almost the same security hole because they were using a common "layer".
