### ISSUE TITLE
more packages needed to install

### ISSUE THREAD

**Issue by peterpt** [reverse-shell/routersploit#163]
This is not an issue , i a just posting to remind you that routersploit needs more modules installed than the ones on requirements.txt .

You should add to requirements.txt :
pexpect==4.2.1
mock==2.0.0

If these modules are not installed then the program will run , but when executes run_tests.sh will reveal the missing modules before like it is in this next image .
https://s28.postimg.org/5r6izj38t/rsploit.png

**Comment by fwkz** [comment]
This two are test requirements, needed for testing and development, since this is not a scope of most user they are excluded from `requirements.txt` file.
