### ISSUE TITLE
bruteforce

### ISSUE THREAD

**Issue by toxydose** [reverse-shell/routersploit#176]
Hi, 
Thank you for your nice program, but I have one bug report.

My router has a basic http login form

I added my router password in your wordlist "passwords.txt"
than:
rsf > use creds/http_basic_bruteforce
rsf (HTTP Basic Bruteforce) > set target http://192.168.1.1
[+] {'target': 'http://192.168.1.1'}

the path has left by default "/"

I saw my password in output, but it says:
[-] Target: http://192.168.1.1:80 worker-7: Authentication Failed - Username: 'admin' Password: '******'

routersploit.log shows an error 401(unauthorised)
2017-02-18 20:08:59,844 DEBUG requests.packages.urllib3.connectionpool       http://192.168.1.1:80 "GET / HTTP/1.1" 401 None

I have added urllib3 it to requirements.txt
and checked the environment again:
pip install -r requirements.txt
urllib3 was installed successfull, all of other equirements was already satisfied
I tried again, but the reaction was the same.

then to check the "/" path and the ability to bruteforce my router,  I tried the same with hydra with the same credentials, same wordlist and the same GET request
hydra -l admin -P passwords.txt 192.168.1.1 -v -V -F  http-get /

hydra bruteforce was successfull.

[80][http-get] host: 192.168.1.1   login: admin   password: ***
[STATUS] attack finished for 192.168.1.1 (valid pair found)

**Comment by fwkz** [comment]
Routersploit internally uses `requests`. Have you tried manually [auth](http://docs.python-requests.org/en/master/user/authentication/) using `requests` to see if it works?

**Comment by toxydose** [comment]
now I have a fix for my issue by adding two modules. I have already wrote the modules and tested it, it works on my router.  Many other routers  bruteforce issue can also be fixed. How can I do the commit by adding my custom modules? I am the new one on Github

**Comment by fwkz** [comment]
@toxydose Please place _Pull Request_. You can find instruction [here](https://help.github.com/articles/creating-a-pull-request/). Please let us know if you need further assistance.

**Comment by 0BuRner** [comment]
If you want to share your fix, you have to create a new branch based on routersploit repository master branch. Then you push your changes on your branch, go back to routersploit github main page and click "pull request" =)

**Comment by toxydose** [comment]
Have I done everything right? The first commit was a mistake, i added an empty files.

**Comment by fwkz** [comment]
@toxydose We will review the changes. ;)

**Comment by toxydose** [comment]
@fwkz Thank you!)

**Comment by fwkz** [comment]
Fixed in #177
