### ISSUE TITLE
Document required python modules

### ISSUE THREAD

**Issue by jfqd** [reverse-shell/routersploit#22]
Thx for making this project! To make it easier for starters a hint on the required python modules in the readme whould be fine. On MacOS X 10.11 I needed to install requests, gnureadline and paramiko via pip.

**Comment by pavs** [comment]
Thanks, this helped me run routersploit on osx.

**Comment by lucyoa** [comment]
We created guide how to install RouterSploit on MacOS X with this commit: 9f39789da02826dfb67c1a85d551147496e594ea
