### ISSUE TITLE
not working on OSX

### ISSUE THREAD

**Issue by ahmadjabr** [reverse-shell/routersploit#269]
hello,

here  details

Ahmads-MacBook-Pro:routersploit-master AhmadJ$ sudo pip install -r requirements.txt
Password:
The directory '/Users/AhmadJ/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/AhmadJ/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting requests>=2.9.1 (from -r requirements.txt (line 1))
  Downloading requests-2.16.0-py2.py3-none-any.whl (85kB)
    100% |████████████████████████████████| 92kB 199kB/s 
Collecting paramiko>=1.16.0 (from -r requirements.txt (line 2))
  Downloading paramiko-2.1.2-py2.py3-none-any.whl (172kB)
    100% |████████████████████████████████| 174kB 248kB/s 
Collecting beautifulsoup4>=4.4.1 (from -r requirements.txt (line 3))
  Downloading beautifulsoup4-4.6.0-py2-none-any.whl (86kB)
    100% |████████████████████████████████| 92kB 351kB/s 
Collecting pysnmp>=4.3.2 (from -r requirements.txt (line 4))
  Downloading pysnmp-4.3.5-py2.py3-none-any.whl (261kB)
    100% |████████████████████████████████| 266kB 253kB/s 
Collecting gnureadline>=6.3.3 (from -r requirements.txt (line 5))
  Downloading gnureadline-6.3.3-cp27-none-macosx_10_9_x86_64.whl (132kB)
    100% |████████████████████████████████| 133kB 294kB/s 
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests>=2.9.1->-r requirements.txt (line 1))
Collecting certifi>=2017.4.17 (from requests>=2.9.1->-r requirements.txt (line 1))
  Downloading certifi-2017.4.17-py2.py3-none-any.whl (375kB)
    100% |████████████████████████████████| 378kB 333kB/s 
Collecting idna<2.6,>=2.5 (from requests>=2.9.1->-r requirements.txt (line 1))
  Downloading idna-2.5-py2.py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 561kB/s 
Collecting urllib3<1.22,>=1.21.1 (from requests>=2.9.1->-r requirements.txt (line 1))
  Downloading urllib3-1.21.1-py2.py3-none-any.whl (131kB)
    100% |████████████████████████████████| 133kB 247kB/s 
Collecting cryptography>=1.1 (from paramiko>=1.16.0->-r requirements.txt (line 2))
  Downloading cryptography-1.8.2-cp27-cp27m-macosx_10_10_intel.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 371kB/s 
Requirement already satisfied: pyasn1>=0.1.7 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from paramiko>=1.16.0->-r requirements.txt (line 2))
Collecting pycryptodome (from pysnmp>=4.3.2->-r requirements.txt (line 4))
  Downloading pycryptodome-3.4.6.tar.gz (6.5MB)
    100% |████████████████████████████████| 6.5MB 113kB/s 
Collecting pysmi (from pysnmp>=4.3.2->-r requirements.txt (line 4))
  Downloading pysmi-0.1.3-py2.py3-none-any.whl (73kB)
    100% |████████████████████████████████| 81kB 363kB/s 
Requirement already satisfied: six>=1.4.1 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 2))
Requirement already satisfied: setuptools>=11.3 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 2))
Collecting cffi>=1.4.1 (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 2))
  Downloading cffi-1.10.0-cp27-cp27m-macosx_10_6_intel.whl (226kB)
    100% |████████████████████████████████| 235kB 410kB/s 
Collecting enum34 (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 2))
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 2))
  Downloading asn1crypto-0.22.0-py2.py3-none-any.whl (97kB)
    100% |████████████████████████████████| 102kB 324kB/s 
Collecting ipaddress (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 2))
  Downloading ipaddress-1.0.18-py2-none-any.whl
Collecting packaging (from cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 2))
  Downloading packaging-16.8-py2.py3-none-any.whl
Collecting ply (from pysmi->pysnmp>=4.3.2->-r requirements.txt (line 4))
  Downloading ply-3.10.tar.gz (150kB)
    100% |████████████████████████████████| 153kB 414kB/s 
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 2))
  Downloading pycparser-2.17.tar.gz (231kB)
    100% |████████████████████████████████| 235kB 462kB/s 
Requirement already satisfied: pyparsing in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from packaging->cryptography>=1.1->paramiko>=1.16.0->-r requirements.txt (line 2))
Installing collected packages: certifi, idna, urllib3, requests, pycparser, cffi, enum34, asn1crypto, ipaddress, packaging, cryptography, paramiko, beautifulsoup4, pycryptodome, ply, pysmi, pysnmp, gnureadline
  Found existing installation: certifi 2017.1.23
    Uninstalling certifi-2017.1.23:
      Successfully uninstalled certifi-2017.1.23
  Running setup.py install for pycparser ... done
  Running setup.py install for pycryptodome ... done
  Running setup.py install for ply ... done
Successfully installed asn1crypto-0.22.0 beautifulsoup4-4.6.0 certifi-2017.4.17 cffi-1.10.0 cryptography-1.8.2 enum34-1.1.6 gnureadline-6.3.3 idna-2.5 ipaddress-1.0.18 packaging-16.8 paramiko-2.1.2 ply-3.10 pycparser-2.17 pycryptodome-3.4.6 pysmi-0.1.3 pysnmp-4.3.5 requests-2.16.0 urllib3-1.21.1
Ahmads-MacBook-Pro:routersploit-master AhmadJ$ ./
.gitignore            Makefile              rsf.py
.travis/              README.md             run_docker.sh
.travis.yml           requirements-dev.txt  run_linter.sh
Dockerfile            requirements.txt      run_tests.sh
LICENSE               routersploit/         tox.ini
Ahmads-MacBook-Pro:routersploit-master AhmadJ$ ./rsf.py 
Traceback (most recent call last):
  File "./rsf.py", line 8, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/Users/AhmadJ/Downloads/routersploit-master/routersploit/__init__.py", line 1, in <module>
    from routersploit.utils import (
  File "/Users/AhmadJ/Downloads/routersploit-master/routersploit/utils/__init__.py", line 40, in <module>
    requests.packages.urllib3.disable_warnings(requests.packages.urllib3.exceptions.InsecureRequestWarning)
AttributeError: 'module' object has no attribute 'packages'
Ahmads-MacBook-Pro:routersploit-master AhmadJ$ sudo ./rsf.py 
Traceback (most recent call last):
  File "./rsf.py", line 8, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/Users/AhmadJ/Downloads/routersploit-master/routersploit/__init__.py", line 1, in <module>
    from routersploit.utils import (
  File "/Users/AhmadJ/Downloads/routersploit-master/routersploit/utils/__init__.py", line 40, in <module>
    requests.packages.urllib3.disable_warnings(requests.packages.urllib3.exceptions.InsecureRequestWarning)
AttributeError: 'module' object has no attribute 'packages'
Ahmads-MacBook-Pro:routersploit-master AhmadJ$

**Comment by TimXcode** [comment]
Same issue :-/

**Comment by GabrielTK** [comment]
Docker too.

**Comment by TimXcode** [comment]
I just tried on Kali and it works like a charm. :-/ Seems to have issues on everything but Kali

**Comment by fwkz** [comment]
Please look at this first.
https://github.com/reverse-shell/routersploit/issues/82
https://github.com/reverse-shell/routersploit/issues/99
https://github.com/reverse-shell/routersploit/issues/69

**Comment by ahmadjabr** [comment]
sudo pip install -r requirements.txt --upgrade

this command solved my issue from 
https://github.com/reverse-shell/routersploit/issues/69

**Comment by sercheo87** [comment]
If installed Anaconda Manager the module gnureadline is named readline.
For execute on OS X change this next section on file **routersploit/routersploit/interpreter.py**  
`import gnureadline as readline`
by
`import readline as readline`

**Comment by fwkz** [comment]
`gnureadline` and `readline` is not the same package. You will get degraded performance using built-in `readline` package on macOS.

**Comment by dade80vr** [comment]
Same error with OS 10.11.6

> pip install RoutersploitInterpreter
> Collecting RoutersploitInterpreter
> Could not find a version that satisfies the requirement RoutersploitInterpreter (from versions: )
> No matching distribution found for RoutersploitInterpreter

Error with RoutersploitInterpreter module? Not solved with "--upgrade".

**Comment by dikidewanto** [comment]
I've edit the section gnureadline to readline then found this : 
sh-3.2# ./rsf.py
Traceback (most recent call last):
  File "./rsf.py", line 35, in <module>
    routersploit()
  File "./rsf.py", line 26, in routersploit
    rsf = RoutersploitInterpreter()
  File "/Users/DikiDewanto/Documents/PENTEST/routersploit/routersploit/interpreter.py", line 176, in __init__
    super(RoutersploitInterpreter, self).__init__()
  File "/Users/DikiDewanto/Documents/PENTEST/routersploit/routersploit/interpreter.py", line 26, in __init__
    self.setup()
  File "/Users/DikiDewanto/Documents/PENTEST/routersploit/routersploit/interpreter.py", line 40, in setup
    readline.read_history_file(self.history_file)
IOError: [Errno 22] Invalid argument

**Comment by jabedude** [comment]
What version of python are you using?
