### ISSUE TITLE
How did you use colors in Python?

### ISSUE THREAD

**Issue by keeganjk** [reverse-shell/routersploit#273]

**Comment by fwkz** [comment]
Please take a look at following code snippet.
https://github.com/reverse-shell/routersploit/blob/master/routersploit/utils/__init__.py#L248

**Comment by keeganjk** [comment]
This only works in Unix, right?

**Comment by lucyoa** [comment]
There are different ANSI escape sequences for Windows

**Comment by keeganjk** [comment]
@lucyoa And what are those?
