### ISSUE TITLE
python-netsnmp package issue

### ISSUE THREAD

**Issue by lampnout** [reverse-shell/routersploit#28]
Trying to install this package to debian, I figured out that the right name of the package is python-pynetsnmp.

**Comment by lampnout** [comment]
on linux 8 works fine

**Comment by lucyoa** [comment]
@lampnout We have a lot of problems with this package and it is only required by one module. I'm going to rewrite creds/snmp_bruteforce.py module by using pysnmp.

**Comment by lucyoa** [comment]
@lampnout We switched to pysnmp with this commit: 67f055540de33bdabf60e4d3bbf6cab9931291ff
