### ISSUE TITLE
Need SSL support

### ISSUE THREAD

**Issue by MidnightSeer** [reverse-shell/routersploit#280]
Certain vulnerabilities, like netgear r7000 command injection are more likely to found on https port 8443.  I manually tested a router, found it to reply back with "ls" output showing that it was vulnerable....but then in routersploit it immediately said the target was not vulnerable...I can only assume this means that it is not trying over ssl.

**Comment by lucyoa** [comment]
Did you try setting prefixing address with https?
```
set target https://<ip>
set port 8443
```

**Comment by lucyoa** [comment]
Closing
