### ISSUE TITLE
Is it possible to Attack on Global IP?

### ISSUE THREAD

**Issue by Deathlive** [reverse-shell/routersploit#290]
Can I attack not through a local IP.
Let's say My local ip → 192.168.1.1 , My global ip → 62.148.128.147.
How can in` Autopwn` `set target 62.148.128.147` and attack is my router?

**Comment by 0BuRner** [comment]
Hi,

You can't do it like that. You have to use a proxy for example (there are probably others ways of doing that). If you don't use proxy, your router will detect you're trying to send network packets to your local network. Your packets will then never be redirected outside your LAN. Thus your WAN IP will never be used.

If you want to test the security of your router from the outside, then like I said, use a proxy or vpn =)

**Comment by Deathlive** [comment]
@0BuRner Okay thanks
