### ISSUE TITLE
Working on tools like routersploit

### ISSUE THREAD

**Issue by arcaniussainey** [reverse-shell/routersploit#291]
So i am making a python tool and i saw that routersploit is able to change the terminal username ie. rsf, autopwn and the color of the prompts. I was wondering how this was done. And i would like to know  how would one contribute to tools like routersploit and other kali tools.

**Comment by 0BuRner** [comment]
Hi, 

In routersploit, it's not a real terminal if I'm not mistaken. It's a simple console output then waiting for new input line.
Something like this:
```
print('rsf >'); // Use special chars to colorize the text
input = readline();
```

To contribute to routersploit project, it's fairly easy: 
1. clone this project
2. create branch
3. make some changes and push them to your branch
4. create pull request

Concerning the kali tools, it depends the tools I guess. Some are open source and probably on github, so it's the same way to contribute. Others are closed sources so you can't. And if you want your tool to be available in Kali, I suppose you have to get in touch with kali admins via the official website and introduce your tool to them.

Hope to see your contributions soon ;-)

**Comment by fwkz** [comment]
Routersploit is based on library called [readline](https://docs.python.org/3.6/library/readline.html). As a good starting point please take a look at built-in method [input](https://docs.python.org/3.6/library/functions.html#input) and study our implementation of [`BaseInterpreter`](https://github.com/reverse-shell/routersploit/blob/master/routersploit/interpreter.py#L20) 😃 

When it comes to contributing to Routersploit please check out our [Contribution Guidelines](https://github.com/reverse-shell/routersploit/wiki/Contribution-Guidelines)
