### ISSUE TITLE
Kali-rolling won't even start.

### ISSUE THREAD

**Issue by Astrades** [reverse-shell/routersploit#300]
Hey guys. So, I cloned it and am in the directory. However, every time I run ./rsf.py I get a python error saying that I don't have a the module 'routersploit.' How do I fix this?

**Comment by somu1795** [comment]
Can you post the entire response or screenshot?

**Comment by Astrades** [comment]
Traceback (most recent call last):
  File "./rsf.py", line 8, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
ImportError: No module named routersploit.interpreter


On Wed, Aug 30, 2017 at 9:10 PM, Saumyakanta Sahoo <notifications@github.com

**Comment by jabedude** [comment]
Run this, then try again.
pip install -r requirements.txt

**Comment by Astrades** [comment]
Well, I tried the obvious step that I should have the first time and I recloned the repo and tried again. Now, it works. Thanks for the attempts at help though, guys.
