### ISSUE TITLE
Routersploit throws an error at startup

### ISSUE THREAD

**Issue by sasatefa2009** [reverse-shell/routersploit#306]
here is the error

/usr/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (dev) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

it's certainly because of routersploit uses an old version of "requests", thus brings with it and old versions of "urrlib3" and "chardet".

So, is there any problem if the "requirements" file were without versions ? to get the latest version ?

**Comment by fwkz** [comment]
We don't have any restriction regarding new version of`requests`.
```
requests>=2.9.1
paramiko>=1.16.0
beautifulsoup4>=4.4.1
pysnmp>=4.3.2
gnureadline>=6.3.3
```
Please check your python environment if it is configured properly.

**Comment by sasatefa2009** [comment]
@fwkz 
My problem comes from 'requests'
Well, the latest version of 'requests' which i also have is 2.18.4 (http://docs.python-requests.org/en/master/)
Also, paramiko is 2.x
beautifulsoup4 is 4.6
pysnmp 4.3.9
gnureadline, this is the only latest library that you use 😄

**Comment by 0BuRner** [comment]
@sasatefa2009 I think you didn't understand what **fwkz** mean: there is no reason that a newer version of "requests" module don't work with routersploit. That's what he said.
In others words, if you're using an newer version of "requests" then great for you, all must goes right :)

**Comment by sasatefa2009** [comment]
@0BuRner Greerings,
Then what is this warming all about ?

**Comment by 0BuRner** [comment]
@sasatefa2009 don't know, might be a bug in one of the latest library you're using :)
You may try to create a virtualenv with the pip install -r requirements.txt command. 
Are you using apt-get to install python modules ?

**Comment by sasatefa2009** [comment]
@0BuRner  a mix of apt-get and pip 😄 
I really don't like the idea of using virtualenv. Tried it once and caused a lot of problems.

**Comment by fwkz** [comment]
I've just created new environment. I got no error. 
```
$ pip install -r requirements.txt
[...]
$ pip freeze
asn1crypto==0.22.0
bcrypt==3.1.3
beautifulsoup4==4.6.0
certifi==2017.7.27.1
cffi==1.10.0
chardet==3.0.4
cryptography==2.0.3
enum34==1.1.6
gnureadline==6.3.3
idna==2.6
ipaddress==1.0.18
paramiko==2.2.1
ply==3.10
pyasn1==0.3.3
pycparser==2.18
pycryptodome==3.4.7
PyNaCl==1.1.2
pysmi==0.1.3
pysnmp==4.3.9
requests==2.18.4
six==1.10.0
urllib3==1.22
```

**Comment by sasatefa2009** [comment]
@fwkz I'm sorry sorry i didn't clarify that, it wasn't for Routersploit. There was a problem at that time in virtualenv.
