### ISSUE TITLE
Pentoo (Gentoo) Linux support

### ISSUE THREAD

**Issue by necrose99** [reverse-shell/routersploit#309]
@Pentoo @Gentoo @Sabayon @Funtoo
**PIP is often Dangerous** on **Gentoo/Sabayon/pentoo/Funtoo** if not in a virtual env...  it can brake many of the system tools ie portage , and other System tools. 
```
#https://github.com/reverse-shell/routersploit/blob/master/requirements.txt 
## for Gentoo 
## Emerge -av package-name.... 

dev-python/beautifulsoup
dev-python/paramiko
dev-python/requests
dev-python/pysnmp

# python-implementation of gnureadline gentoo /or (Gentoo based) has in the base install tarball anyhow.. 
#dev-python/readlike #  optional.

### https://github.com/reverse-shell/routersploit/blob/master/requirements-dev.txt
dev-python/pexpect
virtual/python-mock
dev-python/flake8
```

**Comment by necrose99** [comment]
https://gist.github.com/philippeowagner/6826498 looks promising for a setup.py generator

**Comment by fwkz** [comment]
![travolta](https://media.giphy.com/media/H6KRGhgRMbBwA/giphy.gif)

**Comment by necrose99** [comment]
https://gpo.zugaina.org/ , https://packages.gentoo.org/ 
these are most of the requirements for Gentoo based distro's 

http://tox.readthedocs.io/en/latest/config.html   
**a setup.py /tox.ini would be a plus , as no matter the distro** , packages could be handled, by the distro PM were appropriate.  be it ARCH , RPM, DEB, portage etc.. 
if the depends are thier , install .. make dirs etc.. the pip aspect can be used on some disto's and not others. 
the **setup.py** , would also make making a bash ebuild file specifying  the packages required also trivial..
and or spec for deb or rpm... , however pushing the single script is also doable but if you need to call DIE ..ie new depends... also more reliable, least for ebuilds..  

 https://wiki.gentoo.org/wiki/Pip
**Warning
Running pip as root is not advised. It can render important system tools like emerge useless.[1]**

at the least you can add a Gentoo/Pentoo Building with emerge packages in list above. 

emerge -av dev-python/beautifulsoup dev-python/paramiko dev-python/requests dev-python/pysnmp dev-python/pexpect virtual/python-mockdev-python/flake8

a forked make-file i can do soon ish.  and diff if you'd like.. 
my aim is packaging this..
