### ISSUE TITLE
to make it work on Mac

### ISSUE THREAD

**Issue by FlorinAndrei** [reverse-shell/routersploit#31]
Not an issue per se, just an addendum to the documentation.

Seems to work well on Mac (at least the autopwn part). I only had to install these Python modules:

```
sudo pip install requests paramiko gnureadline
```

Tested on OS X 10.11.4

**Comment by sylvainv** [comment]
Thanks, that worked for me on 10.9.4

**Comment by devsli** [comment]
```sudo pip install -r requirements.txt```

**Comment by JPaulMora** [comment]
If you use anaconda python, the module is called `readline` not `gnureadline` in which case its gonna give you an error even if you have it installed. I'll submit a pull request fixing this error.

**Comment by rgllm** [comment]
That worked for me too. OS X 10.11.5

**Comment by lucyoa** [comment]
We created guide how to install RouterSploit on OS X with this commit: 9f39789da02826dfb67c1a85d551147496e594ea
