### ISSUE TITLE
[root@wyb routersploit-master]# ./rsf.py 

### ISSUE THREAD

**Issue by wuyibin** [reverse-shell/routersploit#350]
Traceback (most recent call last):
  File "./rsf.py", line 8, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/root/Desktop/routersploit-master/routersploit/__init__.py", line 1, in <module>
    from routersploit.utils import (
  File "/root/Desktop/routersploit-master/routersploit/utils/__init__.py", line 6, in <module>
    import importlib
ImportError: No module named importlib

**Comment by bobce79** [comment]
same thing here

**Comment by Deathlive** [comment]
```
pip install -r requirerequirements-dev.txt
pip install -r requirerequirements.txt
```

**Comment by jabedude** [comment]
@wuyibin @bobce79 

`sudo pip install -r requirements.txt`

**Comment by fwkz** [comment]
This is strange, `importlib` is built-in package :<

**Comment by wuyibin** [comment]
@jabedude 
![image](https://user-images.githubusercontent.com/23146418/33769029-786fdaaa-dc63-11e7-8cc4-1ea9de8e748a.png)

**Comment by wuyibin** [comment]
@jabedude 使用了  这条命令  还是出现上面的错误

**Comment by AlexHilgertBRA** [comment]
Do you guys have python 2.7 installed?

```
alex@winOS10:~$ python -V
Python 2.7.12
```

**Comment by wuyibin** [comment]
@AlexHilgertBRA  安装了python 2.7  还是这样

**Comment by AlexHilgertBRA** [comment]
@wuyibin I got this notification in my inbox from you:

![33769029-786fdaaa-dc63-11e7-8cc4-1ea9de8e748a 1](https://user-images.githubusercontent.com/33010754/33807099-e5aa8fec-ddb8-11e7-86fe-5fcbce58dd29.png)

It's calling python 2.6 instead of 2.7, so for me your issue is in there.

Cheers.

**Comment by fwkz** [comment]
@wuyibin Please use python 2.7

**Comment by WoHenShuai233** [comment]
traceback (most recent call last):
  File "./rsf.py", line 8, in <module>
    from routersploit.interpreter import RoutersploitInterpret
r
  File "/home/lyh/routersploit/routersploit/__init__.py", line
1, in <module>
    from routersploit.utils import (
  File "/home/lyh/routersploit/routersploit/utils/__init__.py"
 line 19, in <module>
    import requests
ImportError: No module named requests
