### ISSUE TITLE
Getting Some kind of Error while Modules are Running .. 

### ISSUE THREAD

**Issue by FurqanHanif** [reverse-shell/routersploit#39]
Here See this Screen Shot ... 
Fix these Errors Please...
i am using Linux Mint ... 
[http://i.imgur.com/Gukb3PT.png](url)

**Comment by ArtificialImmunity** [comment]
It seems you don't have the correct module. Try:

`pip install paramiko`

**Comment by fwkz** [comment]
If you have _paramiko_ installed try to upgrade it.
`pip install -U paramiko`

**Comment by FurqanHanif** [comment]
i Installed Python-pip but Still Getting Same Error ... :/

**Comment by fwkz** [comment]
@FurqanHanif Did you install/upgrade _paramiko_ as well?

**Comment by ArtificialImmunity** [comment]
Have you run all of the following commands in this order:

'sudo apt-get install python-pip'
'pip install paramiko'
'pip install -U paramiko'

(if you get errors with the pip installs, try running as sudo)

You can test if it works by opening a terminal and typing:

'python'

To get to a python interpreter and then typing:

'from paramiko.py3compat import u'

If that returns no errors that should have worked. 

If it doesn't work try doing this:

'sudo apt-get install python-dev'
'sudo pip uninstall paramiko'
'sudo pip install -U paramiko'

Then test it again with the previous commands of going into the python interpreter.

Let me know how you get on.

**Comment by FurqanHanif** [comment]
Thanks @ArtificialImmunity  , Problem Fixed...... :D

**Comment by ArtificialImmunity** [comment]
@FurqanHanif Good stuff :)
