### ISSUE TITLE
Tagged release?

### ISSUE THREAD

**Issue by sbrun** [reverse-shell/routersploit#40]
I noted that you made commits mentioning "New release" and the version of the release but it would be great if you could make a tagged release the next time.
I'm packaging routersploit  for distro kali linux and the packaging tools works best with tagged release (we have tools that monitors web pages listing release, and it works well with github pages showing git tags).
Thanks!

**Comment by fwkz** [comment]
@sbrun Tagged and released. Thank you for pointing that out. Let me know if you will need anything else in terms of packaging _RouterSploit_ for _Kali Linux_.

**Comment by sbrun** [comment]
Thank you for the tags. I packaged routersploit without problem. 
It's in kali-rolling now but not tested by the kali team. If you want to check / test, you can install the package routersploit with apt and just run the command routersploit in your shell.
