### ISSUE TITLE
Can't install on Debian. Error code 1 while --compile

### ISSUE THREAD

**Issue by gek0n** [reverse-shell/routersploit#50]
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-TNedkU/gnureadline/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bKAv1O-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-TNedkU/gnureadline/

I had this error when trying to execute "pip install -r requirements.txt"

Don't know how to fix it

**Comment by fwkz** [comment]
_gnureadline_ is required only on OSX. If you are using Debian I believe you are good to go. Just install _requests_, _paramiko_ and _beautifulsoup4_

`sudo pip install requests paramiko beautifulsoup4`

We will update README  with Requirements section to clear all the uncertainties.

**Comment by ArtificialImmunity** [comment]
@gek0n Also, see previous issue for troubleshooting errors #39

**Comment by gek0n** [comment]
I fix this error with 
`sudo apt-get install python-dev`
