### ISSUE TITLE
 ./rsf.py 

### ISSUE THREAD

**Issue by eadistar** [reverse-shell/routersploit#58]
/routersploit# ./rsf.py 
shows followin : 
Traceback (most recent call last):
  File "./rsf.py", line 3, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/home/aditya/routersploit/routersploit/__init__.py", line 1, in <module>
    from routersploit.utils import (
  File "/home/aditya/routersploit/routersploit/utils.py", line 10, in <module>
    import requests
ImportError: No module named requests

**Comment by fwkz** [comment]
You have to install _RouterSploit_ requirements using package manager of your preference. 
e.g.
`pip install -r requirements.txt`

**Comment by ArtificialImmunity** [comment]
Try `pip install requests`

If you get a permission error, Try:
`sudo pip install requests`

**Comment by eadistar** [comment]
after installing : apt-get install python-pip

it's working
