### ISSUE TITLE
Unprintable Characters After Latest Pull

### ISSUE THREAD

**Issue by hyph3n** [reverse-shell/routersploit#63]
I've noticed that after today's pull, I'm getting some unprintable characters in the framework's output. For example, yesterday, if I typed an unknown command, the output was as follows:

rsf > asdf
[-] Unknown command: 'asdf'
rsf > 

After today's pull (37840f3), I get the following output:

rsf > asdf
[-] Unknown command: 'asdf'
rsf > 

---
Fedora 23
Python 2.7.11

EDIT: Adding a screenshot because things look different in the terminal than they do when I paste the text into a browser.

![output](https://cloud.githubusercontent.com/assets/5378617/14905453/b35a821a-0d7e-11e6-910e-ef83a7f54628.png)

**Comment by nymx** [comment]
I am getting the same problem.

**Comment by hyph3n** [comment]
I can see what was added to the code and why (the commit message says it fixes text wrapping onto the same line) but it seems to me these characters should be invisible in the output. . . Unfortunately my Python skills are pretty rudimentary, so I can't propose a solution.

**Comment by nymx** [comment]
@hyph3n I looked at the commit and I can't figure how to fix it. It may be a good idea to switch over to a library written for printing colors to the terminal.

**Comment by fwkz** [comment]
@hyph3n @nymx Fixed in 5e1b7853aae159ed069d362f2eda4e91e29f04f3 Please test.

**Comment by nymx** [comment]
@fwkz It's fixed.
