### ISSUE TITLE
No such file requirements: Ubuntu 

### ISSUE THREAD

**Issue by EdwardGoomba** [reverse-shell/routersploit#64]
When doing the step pip install -r requirements an error gets thrown: 'Could not open requirements file: [Errno 2] No such file or directory: 'requirements'.

If you run pip install -r requirements.txt however it runs fine. Running on Ubuntu

**Comment by lucyoa** [comment]
Fixed with this commit: 0212c8272c6f19c88132ad7ae0081dd94d0ce76f
