### ISSUE TITLE
Doesn't work well on NetHunter 3.0

### ISSUE THREAD

**Issue by MatthewHKnight** [reverse-shell/routersploit#70]
So I've tried to run routersploit on NetHunter 3.0 on a Nexus 6 appears NetHunter is missing paramiko not 100% sure how that can be install or if it even can be installed on NetHunter 3.0 or not. but after I did the run it started to check my router to see if it was vulnerable and then it errored out about paramiko being a missing module.

**Comment by lucyoa** [comment]
@MatthewHKnight Try this:
```
sudo apt-get install python-dev python-pip libncurses5-dev git
git clone https://github.com/reverse-shell/routersploit
cd routersploit
pip install -r requirements.txt
./rsf.py
```

**Comment by MatthewHKnight** [comment]
Getting this error now
http://i.imgur.com/IyvY03c.png

**Comment by IMcPwn** [comment]
@MatthewHKnight It looks like you don't have setuptools installed. I'm not sure if setuptools_ext is a part of that but the following couldn't hurt:

`pip install setuptools`

**Comment by MatthewHKnight** [comment]
Now i'm getting ImportError: connect import name util after running the autopwn I got setuptools installed now but the new error is the one I just post here.

**Comment by lucyoa** [comment]
Unfortunately I don't have necessary device to set up NetHunter and test it by myself.

**Comment by Lexus89** [comment]
I just installed it on my Nexus 5 and it works great. Just wanted to let you know, hopefully issue is resolved now.

**Comment by fwkz** [comment]
@Lexus89 Thanks for letting us know. 🙇
