### ISSUE TITLE
Dsl_2570b_info_disclosure false positive

### ISSUE THREAD

**Issue by Bry-fi** [reverse-shell/routersploit#78]
So I ran this module on my router and it said "credentials could not be retrieved" even though the 'check' command said that the target is vulnerabld

**Comment by Bry-fi** [comment]
Vulnerable*

**Comment by lucyoa** [comment]
@Bry-fi could you give information what kind of router do you have?

Please check http://ip:port/hidden_info.html on your device and what it returns.

**Comment by Bry-fi** [comment]
Model: TG1682G
Vendor: ARRIS Group, Inc.

**Comment by lucyoa** [comment]
@Bry-fi what response you get: http://ip:port/hidden_info.html

**Comment by Bry-fi** [comment]
@lucyoa There is no hidden info html file on my router if thats what you are refering you

**Comment by lucyoa** [comment]
@Bry-fi I added fix with this commit: ff0f1a00672e0a40c67369bcc5fe86f8bfc87d8e Please check if it works correctly

**Comment by lucyoa** [comment]
Closing
