### ISSUE TITLE
Additional packages needed on Ubuntu 16

### ISSUE THREAD

**Issue by butla** [reverse-shell/routersploit#83]
I was installing routersploit on a relatively clean Kubuntu 16 and I've noticed that some packages are missing from installation instructions in README, namely: libffi-dev and libssl-dev.

Cheers!

**Comment by fwkz** [comment]
Thanks for suggestion! Requirements stated in README have it's dependencies too, we can't keep track of them in all flavors of Linux.

**Comment by butla** [comment]
Well, didn't you want to provide just that for Ubuntu? :) I'm saying about the line with `sudo apt-get install python-dev python-pip libncurses5-dev git`. I don't think that versions earlier than 16.04 had libffi-dev and libssl-dev. And Kubuntu differs only in GUI packages and some desktop tools.
