### ISSUE TITLE
Ctrl+C new prompt

### ISSUE THREAD

**Issue by lucyoa** [reverse-shell/routersploit#90]
Ctrl+C should not close the application. It should display new prompt (identical behaviour like in bash):
```
root@kalidev:~/git/routersploit# ^C
root@kalidev:~/git/routersploit# ^C
root@kalidev:~/git/routersploit# ^C
```

**Comment by fwkz** [comment]
Introduced in 1444f4f19830ec36091725333062e5dcc72188dc
