### ISSUE TITLE
Add setg ?

### ISSUE THREAD

**Issue by dtest505** [reverse-shell/routersploit#97]
Would love a setg like in metaploit.
Its nice to have a target, threads, etc. set globally as you jump to different modules and such.

**Comment by lucyoa** [comment]
Yea, that would be cool feature. We gonna implement this. Thanks

**Comment by fwkz** [comment]
@lucyoa `setg` value should be used over the default value?

**Comment by lucyoa** [comment]
@fwkz yes, default value should be overwritten

**Comment by fwkz** [comment]
Ready for first tests in [feature branch](https://github.com/reverse-shell/routersploit/tree/setg).

**Comment by fwkz** [comment]
I have pushed all changes to _master_.
